### ISSUE TITLE
Auth broken

### ISSUE THREAD

**Issue by h4sh5** [peterjmorgan/Syringe#10]
I keep getting this error message (in LOG_Syringe.log) even tho my phylum token is valid:

```
❗ Error: HTTP request error (403 Forbidden):\n\naccess forbidden, insufficient privileges, re-authentication will not help\n"
```

I have a suspicion that it's due to the current repo not being in-sync with the go-phylum library, and the go-phylum library is not in sync w/ the current way the platform does auth (the version is out of date, and even after manually bumping it to v0.1.7 it still breaks; the current version in go.mod v0.1.0 throws different errors such as a 404 for the openid configuration endpoint)

**Comment by h4sh5** [comment]
if I don’t manually bump the go-phylum version, then I get this error instead:

```
./Syringe  list-projects
failed to get oidc provider: 404 Not Found: {"error":"RESTEASY003210: Could not find resource for full path: https://login.phylum.io/auth/realms/phylum/.well-known/openid-configuration"}
Failed to get access token: 404 Not Found: {"error":"RESTEASY003210: Could not find resource for full path: https://login.phylum.io/auth/realms/phylum/.well-known/openid-configuration"}
```

**Comment by peterjmorgan** [comment]
@h4sh5 This should be fixed in https://github.com/peterjmorgan/Syringe/commit/a3bfce18d4c06646b2378b983870caf32c05a2dc
